### ISSUE TITLE
Configurable error handler

### ISSUE THREAD

**Issue by smee** [s1ck/gdl#24]
Currently the ANTLR parser uses the default error strategy `org.antlr.v4.runtime.DefaultErrorStrategy` which just prints to the standard error for each parse error but continues the parsing. The user has no way of knowing/reacting to syntax errors.
If there was a way of specifying an alternative error strategy, for example `org.antlr.v4.runtime.BailErrorStrategy` via `org.antlr.v4.runtime.Parser.setErrorHandler(ANTLRErrorStrategy)` the user could choose to wrap the parser in a try/catch-block an catch `org.antlr.v4.runtime.misc.ParseCancellationException.ParseCancellationException(Throwable)`.

**Comment by s1ck** [comment]
Good point, will add.
