### ISSUE TITLE
GDL to Maven Central

### ISSUE THREAD

**Issue by merando** [s1ck/gdl#31]
Would be great to reduce the necessary configuration overhead to use GDL by adding it to the maven central instead of our "special" solution as we discussed it in our gradoop-team-meeting.

**Comment by s1ck** [comment]
I will look into it. Are you using GDL standalone? For gradoop, you'll still need the repository configuration in your poms.

**Comment by merando** [comment]
Yeah I know, a similar ticket exists for gradoop. We want to reduce the necessary administration effort since Kevin has to be replaced when he finishes his thesis

**Comment by galpha** [comment]
I'll prepare gdl to deploy it to maven central. You can assign me for that.

**Comment by galpha** [comment]
GDL is now deployed to Maven Central, here in shot some useful commands:

mvn clean verify -Prelease (will test the project + test deployment plugins but does NOT upload artifacts)
mvn clean deploy (will test the project + upload artifacts)
mvn clean verify (will test the project but NOT deployment plugins (configuration for travis ci))
