### ISSUE TITLE
Support unlabeled nodes

### ISSUE THREAD

**Issue by pstutz** [s1ck/gdl#36]
Would fix https://github.com/opencypher/cypher-for-apache-spark/issues/143

**Comment by s1ck** [comment]
What does `vertex.getLabel()` need to return in that case? `null` or an empty string?

**Comment by pstutz** [comment]
An empty set?

**Comment by pstutz** [comment]
Or an Option.

**Comment by Mats-SX** [comment]
Just noting that the empty string is an invalid label from Cypher's POV, so that could be used (I use it in the schema model for example).
