### ISSUE TITLE
Bug in complex NOT predicates

### ISSUE THREAD

**Issue by lc0197** [s1ck/gdl#53]
Queries conjoining a NOT predicate are not handled correctly.
E.g., the query 
`MATCH (alice)-[r]->(bob) WHERE bob.age<30 AND NOT alice.age > 50` 
yields the predicate
`(alice.age > 50 AND (NOT bob.age < 30))` 
in `GDLLoader.java`. 

I think this is due to confusion of FIFO/LIFO functionality in `GDLLoader::exitNotExpression`
Changing line 561 in `GDLLoader.java` from 

`Predicate not = new Not(currentPredicates.pop());` 

to 

`Predicate not = new Not(currentPredicates.removeLast());` 

fixed this issue for me, test cases still worked after this change.

**Comment by s1ck** [comment]
Nice find. Would you mind opening a PR for the fix? Thanks.

**Comment by lc0197** [comment]
OK, but I just stumbled upon another possible issue (not sure, if it is one): 
The `Comparator::getInverse` that inverts a comparator looks like 

...
`case LT:   return GT;`

`case GT:   return LT;`

`case LTE:  return GTE;`

`case GTE:  return LTE;`
....

In my intuition, the inverse of `LT` should be `GTE` and similarly the other inverses (`GT ->LTE, LTE->GT, GTE->LT`). 
Is this intuition correct? If so, I could quickly fix that, too.

**Comment by galpha** [comment]
Fits my intuition as well. But I prefer to discuss this in a new issue. Here you should only provide a fix for the NOT predicate.

**Comment by s1ck** [comment]
I agree with @galpha Let's open another issue / PR for the inverse operations. Thanks @lc0197

**Comment by galpha** [comment]
fixed in #54
